inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/**
    - vendor/**/*
    - node_modules/**/*
  DisplayCopNames: true

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - Guardfile
    - config/environments/**/*
    - db/seeds.rb
    - config/routes.rb

Style/Documentation:
  Exclude:
    - 'app/controllers/*'
    - 'app/helpers/*'
    - 'app/models/*'
    - 'app/mailers/*'
    - 'config/application.rb'

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Metrics/AbcSize:
  Exclude:
    - db/migrate/*
